name: CI
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'go.mod'
      - name: Format
        run: make fmt
      - name: Vet
        run: make vet
      - name: Test
        run: make test
