name: CI-post-merge
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Cache fonts
        id: cache
        uses: actions/cache@v4
        with:
          path: font
          key: ${{ runner.os }}-font-${{ hashFiles('font/*.ttf') }}
          restore-keys: |
            ${{ runner.os }}-font-

      - name: Run test
        shell: bash
        run: ./test.sh


  update-tag:
    runs-on: ubuntu-latest
    needs: run-test
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor


  publish-binary:
    runs-on: ubuntu-latest
    needs: update-tag
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: v${{ needs.update-tag.outputs.new_version }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}